name: onion work
on:
#  schedule:
#    - cron:  '0 */8 * * *'
  issue_comment:
    types: [created]
jobs:
 StartWorks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_dirs.outputs.matrix}}
    steps:  
    - uses: actions/checkout@v2
      with:
       repository: workerVA/basePlace
       token: ${{ secrets.ACCESS_TOKEN }}
       ref: devTools
       path: devTools
    - id: list_dirs
      run: echo "::set-output name=matrix::$(ls devTools/workModuleRun/*.py|jq -cnR '[inputs | select(length>0)]')"
 ManyWorks:
    runs-on: ubuntu-latest
    needs: StartWorks
    strategy:
      fail-fast: false
      matrix:
        job: ${{fromJson(needs.StartWorks.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v2
      with:
       repository: workerVA/basePlace
       token: ${{ secrets.ACCESS_TOKEN }}
       ref: devTools
       path: devTools
    - name: start $JOB
      run: |
          sudo python3 $JOB
      env:
        JOB: ${{ matrix.job }}
 EndWorks:
    runs-on: ubuntu-latest
#    if: always()
    needs: ManyWorks 
    steps:
      - name: check
        run: |
          echo "endWorks this push"
          pwd
          ls
      - name: start time
        run: |
          date
